/* This file is generated by zits. Do not edit manually */

export enum TaskerUnitEnum {
	TaskList = 'TaskList',
	TaskItem = 'TaskItem',
}

/** List of all Link types handled by this Zome */
export enum TaskerLinkType {
	Default = 'Default',
	Path = 'Path',
	TaskLists = 'TaskLists',
	Locked = 'Locked',
	Completed = 'Completed',
	Item = 'Item',
}
