/* This file is generated by zits. Do not edit manually */

// @ts-ignore
import {TaskerEntry, CreateTaskItemInput, GetAgentInput, GetAhInput, GetDataTypeInput, GetDhInput, GetEhInput, GetLhInput, GetManyAgentInput, GetManyAhInput, GetManyDhInput, GetManyEhInput, GetManyLhInput, TaskItem, TaskList, } from './tasker.types';
// @ts-ignore
import {
/** api/common.ts */
// @ts-ignore
WebsocketConnectionOptions, WsClientOptions, HolochainError, CloneIdHelper,
/** types.ts */
// @ts-ignore
KitsuneAgent, KitsuneSpace, HoloHashB64, AgentPubKeyB64, DnaHashB64, WasmHashB64, EntryHashB64, ActionHashB64, AnyDhtHashB64, InstalledAppId, Signature, CellId, DnaProperties, RoleName, InstalledCell, Timestamp, HoloHashed, FetchPoolInfo,
/** hdk/action.ts */
// @ts-ignore
SignedAction, SignedActionHashed, RegisterAgentActivity, ActionHashed, ActionType, Action, NewEntryAction, Dna, AgentValidationPkg, InitZomesComplete, CreateLink, DeleteLink, OpenChain, CloseChain, Update, Delete, Create,
/** hdk/capabilities.ts */
// @ts-ignore
CapSecret, CapClaim, GrantedFunctionsType, GrantedFunctions, ZomeCallCapGrant, CapAccess, CapGrant,
///** hdk/countersigning.ts */
//CounterSigningSessionData,
//PreflightRequest,
//CounterSigningSessionTimes,
//ActionBase,
//CounterSigningAgents,
//PreflightBytes,
//Role,
//CountersigningAgentState,
/** hdk/dht-ops.ts */
// @ts-ignore
ChainOpType, DhtOp, WarrantOp, ChainOp, Warrant, ChainIntegrityWarrant, ValidationType, ActionHashAndSig,
/** hdk/entry.ts */
// @ts-ignore
EntryVisibility, AppEntryDef, EntryType, EntryContent, Entry,
/** hdk/record.ts */
// @ts-ignore
Record as HcRecord, RecordEntry as HcRecordEntry,
/** hdk/link.ts */
//AnyLinkableHash,
// @ts-ignore
ZomeIndex, LinkType, LinkTag, RateWeight, RateBucketId, RateUnits, Link,
/** api/admin/types.ts */
// @ts-ignore
// YamlProperties
Zomes, WasmCode, CapGrantInfo, PeerMetaInfo, DisabledAppReason, AppStatus, StemCell, ProvisionedCell, ClonedCell, CellType, CellInfo, AppInfo, MembraneProof, MemproofMap, RoleSettingsMap, RoleSettings, DnaModifiersOpt, DnaModifiers, FunctionName, ZomeName, ZomeDefinition, IntegrityZome, CoordinatorZome, DnaDefinition, ResourceBytes, ResourceMap, CellProvisioningStrategy, CellProvisioning, DnaVersionSpec, DnaVersionFlexible, AppRoleDnaManifest, AppRoleManifest, AppManifest, AppBundle, AppBundleSource, NetworkSeed, AppStatusFilter, AppInterfaceInfo, AgentInfoSigned, ZomeLocation, DnaManifest,
} from '@holochain/client';


/// Simple Hashes
// @ts-ignore
type AgentArray = Uint8Array;
// @ts-ignore
type DnaArray = Uint8Array;
// @ts-ignore
type WasmArray = Uint8Array;
// @ts-ignore
type EntryArray = Uint8Array;
// @ts-ignore
type ActionArray = Uint8Array;
// @ts-ignore
type AnyDhtArray = Uint8Array;
// @ts-ignore
type AnyLinkableArray = Uint8Array;
// @ts-ignore
type ExternalArray = Uint8Array;

// @ts-ignore
import {
/** Common */
// @ts-ignore
DhtOpHashB64, DhtOpHash,
/** DnaFile */
// @ts-ignore
DnaFile,
/** entry */
// @ts-ignore
EntryDefLocation, EntryDefLocationType, AppEntryDefLocation, GetOptions, GetStrategy,
/** entry-details */
// @ts-ignore
EntryDetails, RecordDetails, Details, DetailsType, EntryDhtStatus,
/** Validation */
// @ts-ignore
ValidationStatus, ValidationReceipt,
} from '@holochain-open-dev/core-types';

import {ZomeProxy} from '@ddd-qc/lit-happ';
import {taskerFunctionNames} from './tasker.fn';
import {TaskerUnitEnum} from './tasker.integrity';
import {TaskerLinkType} from './tasker.integrity';

/**
 *
 */
export class TaskerProxy extends ZomeProxy {
  static override readonly DEFAULT_ZOME_NAME = "zTasker";
  static override readonly FN_NAMES = taskerFunctionNames;
  static override readonly ENTRY_TYPES = Object.values(TaskerUnitEnum);
  static override readonly LINK_TYPES = Object.values(TaskerLinkType);
 
  async getMyAgentKeyEntryHash(): Promise<AnyLinkableArray> {
    return this.call('get_my_agent_key_entry_hash', null);
  }

  async getRecordAuthorLocal(dh: AnyDhtArray): Promise<AgentArray> {
    return this.call('get_record_author_local', dh);
  }

  async getRecordAuthorNetwork(dh: AnyDhtArray): Promise<AgentArray> {
    return this.call('get_record_author_network', dh);
  }

  async getRecordLocal(hash: AnyDhtArray): Promise<HcRecord | null> {
    return this.call('get_record_local', hash);
  }

  async getRecordNetwork(hash: AnyDhtArray): Promise<HcRecord | null> {
    return this.call('get_record_network', hash);
  }

  async getAhLocal(eh: EntryArray): Promise<ActionArray | null> {
    return this.call('get_ah_local', eh);
  }

  async getAhNetwork(eh: EntryArray): Promise<ActionArray | null> {
    return this.call('get_ah_network', eh);
  }

  async getDataType(input: GetDataTypeInput): Promise<string> {
    return this.call('get_data_type', input);
  }

  async createTaskList(title: string): Promise<ActionArray> {
    return this.call('create_task_list', title);
  }

  async createTaskItem(input: CreateTaskItemInput): Promise<ActionArray> {
    return this.call('create_task_item', input);
  }

  async completeTask(taskEh: EntryArray): Promise<ActionArray> {
    return this.call('complete_task', taskEh);
  }

  async isListLocked(listEh: EntryArray): Promise<boolean> {
    return this.call('is_list_locked', listEh);
  }

  async getTaskItem(eh: EntryArray): Promise<[TaskItem, boolean] | null> {
    return this.call('get_task_item', eh);
  }

  async getListItems(listEh: EntryArray): Promise<[EntryArray, TaskItem, boolean][]> {
    return this.call('get_list_items', listEh);
  }

  async getAllLists(strategy: GetStrategy): Promise<[EntryArray, TaskList][]> {
    return this.call('get_all_lists', strategy);
  }
}
