/* This file is generated by zits. Do not edit manually */

export enum ProfilesAltUnitEnum {
	Profile = 'Profile',
}

export enum ProfilesAltLinkType {
	PrefixPath = 'PrefixPath',
	PathToAgent = 'PathToAgent',
	AgentToProfile = 'AgentToProfile',
}
