/* This file is generated by zits. Do not edit manually */

// @ts-ignore
import {EntryTypes, Signal, Profile, ZomeFnInput, } from './profiles.types';
// @ts-ignore
import {
/** api/common.ts */
// @ts-ignore
WebsocketConnectionOptions, WsClientOptions, HolochainError, CloneIdHelper,
/** types.ts */
// @ts-ignore
KitsuneAgent, KitsuneSpace, HoloHashB64, AgentPubKeyB64, DnaHashB64, WasmHashB64, EntryHashB64, ActionHashB64, AnyDhtHashB64, InstalledAppId, Signature, CellId, DnaProperties, RoleName, InstalledCell, Timestamp, HoloHashed, FetchPoolInfo,
/** hdk/action.ts */
// @ts-ignore
SignedAction, SignedActionHashed, RegisterAgentActivity, ActionHashed, ActionType, Action, NewEntryAction, Dna, AgentValidationPkg, InitZomesComplete, CreateLink, DeleteLink, OpenChain, CloseChain, Update, Delete, Create,
/** hdk/capabilities.ts */
// @ts-ignore
CapSecret, CapClaim, GrantedFunctionsType, GrantedFunctions, ZomeCallCapGrant, CapAccess, CapGrant,
///** hdk/countersigning.ts */
//CounterSigningSessionData,
//PreflightRequest,
//CounterSigningSessionTimes,
//ActionBase,
//CounterSigningAgents,
//PreflightBytes,
//Role,
//CountersigningAgentState,
/** hdk/dht-ops.ts */
// @ts-ignore
ChainOpType, DhtOp, WarrantOp, ChainOp, Warrant, ChainIntegrityWarrant, ValidationType, ActionHashAndSig,
/** hdk/entry.ts */
// @ts-ignore
EntryVisibility, AppEntryDef, EntryType, EntryContent, Entry,
/** hdk/record.ts */
// @ts-ignore
Record as HcRecord, RecordEntry as HcRecordEntry,
/** hdk/link.ts */
//AnyLinkableHash,
// @ts-ignore
ZomeIndex, LinkType, LinkTag, RateWeight, RateBucketId, RateUnits, Link,
/** api/admin/types.ts */
// @ts-ignore
// YamlProperties
Zomes, WasmCode, CapGrantInfo, PeerMetaInfo, DisabledAppReason, AppStatus, StemCell, ProvisionedCell, ClonedCell, CellType, CellInfo, AppInfo, MembraneProof, MemproofMap, RoleSettingsMap, RoleSettings, DnaModifiersOpt, DnaModifiers, FunctionName, ZomeName, ZomeDefinition, IntegrityZome, CoordinatorZome, DnaDefinition, ResourceBytes, ResourceMap, CellProvisioningStrategy, CellProvisioning, DnaVersionSpec, DnaVersionFlexible, AppRoleDnaManifest, AppRoleManifest, AppManifest, AppBundle, AppBundleSource, NetworkSeed, AppStatusFilter, AppInterfaceInfo, AgentInfoSigned, ZomeLocation, DnaManifest,
} from '@holochain/client';


/// Simple Hashes
// @ts-ignore
type AgentArray = Uint8Array;
// @ts-ignore
type DnaArray = Uint8Array;
// @ts-ignore
type WasmArray = Uint8Array;
// @ts-ignore
type EntryArray = Uint8Array;
// @ts-ignore
type ActionArray = Uint8Array;
// @ts-ignore
type AnyDhtArray = Uint8Array;
// @ts-ignore
type AnyLinkableArray = Uint8Array;
// @ts-ignore
type ExternalArray = Uint8Array;

// @ts-ignore
import {
/** Common */
// @ts-ignore
DhtOpHashB64, DhtOpHash,
/** DnaFile */
// @ts-ignore
DnaFile,
/** entry */
// @ts-ignore
EntryDefLocation, EntryDefLocationType, AppEntryDefLocation, GetOptions, GetStrategy,
/** entry-details */
// @ts-ignore
EntryDetails, RecordDetails, Details, DetailsType, EntryDhtStatus,
/** Validation */
// @ts-ignore
ValidationStatus, ValidationReceipt,
} from '@holochain-open-dev/core-types';

/** User defined external dependencies */
// @ts-ignore
import {ProfilesLinkType as LinkTypes} from "./profiles.integrity"

import {ZomeProxy} from '@ddd-qc/lit-happ';
import {profilesFunctionNames} from './profiles.fn';
import {ProfilesUnitEnum} from './profiles.integrity';
import {ProfilesLinkType} from './profiles.integrity';

/**
 *
 */
export class ProfilesProxy extends ZomeProxy {
  static override readonly DEFAULT_ZOME_NAME = "profiles";
  static override readonly FN_NAMES = profilesFunctionNames;
  static override readonly ENTRY_TYPES = Object.values(ProfilesUnitEnum);
  static override readonly LINK_TYPES = Object.values(ProfilesLinkType);
 
  async createProfile(profile: Profile): Promise<HcRecord> {
    return this.call('create_profile', profile);
  }

  async updateProfile(profile: Profile): Promise<HcRecord> {
    return this.call('update_profile', profile);
  }

  async searchAgents(nicknameFilter: string): Promise<AgentArray[]> {
    return this.call('search_agents', nicknameFilter);
  }

  async getMyProfile(): Promise<HcRecord | null> {
    return this.call('get_my_profile', null);
  }

  async getAgentProfile(input: AgentArray): Promise<HcRecord | null> {
    return this.call('get_agent_profile', input);
  }

  async getAgentsWithProfile(input: void): Promise<AgentArray[]> {
    return this.call('get_agents_with_profile', input);
  }
}
