/* This file is generated by zits. Do not edit manually */

export enum ProfilesUnitEnum {
	Profile = 'Profile',
}

export enum ProfilesLinkType {
	PrefixPath = 'PrefixPath',
	PathToAgent = 'PathToAgent',
	AgentToProfile = 'AgentToProfile',
}
