/* This file is generated by zits. Do not edit manually */

import {ZomeName, FunctionName} from '@holochain/client';


/** Array of all zome function names in "agentDirectory" */
export const agentDirectoryFunctionNames: FunctionName[] = [
	"entry_defs", 
	"get_zome_info", 
	"get_dna_info",
	"get_registered_agents",
];


/** Generate tuple array of function names with given zomeName */
export function generateAgentDirectoryZomeFunctionsArray(zomeName: ZomeName): [ZomeName, FunctionName][] {
   const fns: [ZomeName, FunctionName][] = [];
   for (const fn of agentDirectoryFunctionNames) {
      fns.push([zomeName, fn]);
   }
   return fns;
}


/** Tuple array of all zome function names with default zome name "agent_directory" */
export const agentDirectoryZomeFunctions: [ZomeName, FunctionName][] = generateAgentDirectoryZomeFunctionsArray("agent_directory");
