/* This file is generated by zits. Do not edit manually */


/** All link types specific to this Zome */
export enum AgentDirectoryLinkType {
	Agent = 'Agent',
}
export enum AgentDirectoryUnitEnum {
	Stub = 'Stub',
}
