/* This file is generated by zits. Do not edit manually */

import {ZomeName, FunctionName} from '@holochain/client';


/** Array of all zome function names in "real" */
export const realFunctionNames: FunctionName[] = [
	"entry_defs", 
	"get_zome_info", 
	"get_dna_info",
	"get_real",
	"create_real",
	"get_my_reals",
];


/** Generate tuple array of function names with given zomeName */
export function generateRealZomeFunctionsArray(zomeName: ZomeName): [ZomeName, FunctionName][] {
   const fns: [ZomeName, FunctionName][] = [];
   for (const fn of realFunctionNames) {
      fns.push([zomeName, fn]);
   }
   return fns;
}


/** Tuple array of all zome function names with default zome name "zReal" */
export const realZomeFunctions: [ZomeName, FunctionName][] = generateRealZomeFunctionsArray("zReal");
