/* This file is generated by zits. Do not edit manually */

// @ts-ignore
import {DEFAULT_COORDINATOR_ZOME_NAME, DEFAULT_INTEGRITY_ZOME_NAME, ROOT_ANCHOR_SHAREDS, SharedOwnershipEntry, AppTip, OfferOwnershipInput, PublishOwnershipInput, RecvKeyInput, RequestKeyInput, RequestOwnershipInput, SendKeyInput, SharedKey, TagOwner, TagShared, } from './sharedOwnership.types';
// @ts-ignore
import {
/** api/common.ts */
// @ts-ignore
WebsocketConnectionOptions, WsClientOptions, HolochainError, CloneIdHelper,
/** types.ts */
// @ts-ignore
KitsuneAgent, KitsuneSpace, HoloHashB64, AgentPubKeyB64, DnaHashB64, WasmHashB64, EntryHashB64, ActionHashB64, AnyDhtHashB64, InstalledAppId, Signature, CellId, DnaProperties, RoleName, InstalledCell, Timestamp, Duration, HoloHashed, FetchPoolInfo,
/** hdk/action.ts */
// @ts-ignore
SignedAction, SignedActionHashed, RegisterAgentActivity, ActionHashed, ActionType, Action, NewEntryAction, Dna, AgentValidationPkg, InitZomesComplete, CreateLink, DeleteLink, OpenChain, CloseChain, Update, Delete, Create,
/** hdk/capabilities.ts */
// @ts-ignore
CapSecret, CapClaim, GrantedFunctionsType, GrantedFunctions, ZomeCallCapGrant, CapAccess, CapGrant,
///** hdk/countersigning.ts */
//CounterSigningSessionData,
//PreflightRequest,
//CounterSigningSessionTimes,
//ActionBase,
//CounterSigningAgents,
//PreflightBytes,
//Role,
//CountersigningAgentState,
/** hdk/dht-ops.ts */
// @ts-ignore
ChainOpType, DhtOp, WarrantOp, ChainOp, Warrant, ChainIntegrityWarrant, ValidationType, ActionHashAndSig,
/** hdk/entry.ts */
// @ts-ignore
EntryVisibility, AppEntryDef, EntryType, EntryContent, Entry,
/** hdk/record.ts */
// @ts-ignore
Record as HcRecord, RecordEntry as HcRecordEntry,
/** hdk/link.ts */
//AnyLinkableHash,
// @ts-ignore
ZomeIndex, LinkType, LinkTag, RateWeight, RateBucketId, RateUnits, Link,
/** api/admin/types.ts */
// @ts-ignore
// YamlProperties
Zomes, WasmCode, DisabledAppReason, AppInfoStatus, StemCell, ProvisionedCell, ClonedCell, CellType, CellInfo, AppInfo, MembraneProof, MemproofMap, RoleSettingsMap, RoleSettings, DnaModifiersOpt, DnaModifiers, FunctionName, ZomeName, ZomeDefinition, IntegrityZome, CoordinatorZome, DnaDefinition, ResourceBytes, ResourceMap, CellProvisioningStrategy, CellProvisioning, DnaVersionSpec, DnaVersionFlexible, AppRoleDnaManifest, AppRoleManifest, AppManifest, AppBundle, AppBundleSource, NetworkSeed, AppStatusFilter, AppInterfaceInfo, AgentInfoSigned, ZomeLocation, DnaManifest,
} from '@holochain/client';


/// Simple Hashes
// @ts-ignore
type AgentArray = Uint8Array;
// @ts-ignore
type DnaArray = Uint8Array;
// @ts-ignore
type WasmArray = Uint8Array;
// @ts-ignore
type EntryArray = Uint8Array;
// @ts-ignore
type ActionArray = Uint8Array;
// @ts-ignore
type AnyDhtArray = Uint8Array;
// @ts-ignore
type AnyLinkableArray = Uint8Array;
// @ts-ignore
type ExternalArray = Uint8Array;

// @ts-ignore
import {
/** Common */
// @ts-ignore
DhtOpHashB64, DhtOpHash,
/** DnaFile */
// @ts-ignore
DnaFile, DnaDef,
/** entry-details */
// @ts-ignore
EntryDetails, RecordDetails, Details, DetailsType, EntryDhtStatus,
/** Validation */
// @ts-ignore
ValidationStatus, ValidationReceipt,
} from '@holochain-open-dev/core-types';

import {ZomeProxy} from '@ddd-qc/lit-happ';
import {sharedOwnershipFunctionNames} from './sharedOwnership.fn';
import {SharedOwnershipUnitEnum, SharedOwnershipLinkType} from './sharedOwnership.integrity';

/**
 *
 */
export class SharedOwnershipProxy extends ZomeProxy {
  static override readonly DEFAULT_ZOME_NAME = "zSharedOwnership";
  static override readonly FN_NAMES = sharedOwnershipFunctionNames;
  static override readonly ENTRY_TYPES = Object.values(SharedOwnershipUnitEnum);
  static override readonly LINK_TYPES = Object.values(SharedOwnershipLinkType);
 
  async getRecordAuthor(dh: AnyDhtArray): Promise<AgentArray> {
    return this.call('get_record_author', dh);
  }

  async publishOwnership(input: PublishOwnershipInput): Promise<[ActionArray, ActionArray]> {
    return this.callBlocking('publish_ownership', input);
  }

  async probeShareds(): Promise<ActionArray[]> {
    return this.call('probe_shareds', null);
  }

  async probeOwners(sharedAh: ActionArray): Promise<[AgentArray, ActionArray][]> {
    return this.call('probe_owners', sharedAh);
  }

  async createSharedKey(): Promise<ActionArray> {
    return this.callBlocking('create_shared_key', null);
  }

  async sendSharedKey(input: SendKeyInput): Promise<void> {
    return this.callBlocking('send_shared_key', input);
  }

  async requestSharedKey(input: RequestKeyInput): Promise<void> {
    return this.call('request_shared_key', input);
  }

  async querySharedKeys(): Promise<ActionArray[]> {
    return this.call('query_shared_keys', null);
  }

  async offerOwnership(input: OfferOwnershipInput): Promise<void> {
    return this.call('offer_ownership', input);
  }

  async requestOwnership(input: RequestOwnershipInput): Promise<void> {
    return this.call('request_ownership', input);
  }
}
