/* This file is generated by zits. Do not edit manually */

import {ZomeName, FunctionName} from '@holochain/client';


/** Array of all zome function names in "sharedOwnership" */
export const sharedOwnershipFunctionNames: FunctionName[] = [
	"entry_defs", 
	"get_zome_info", 
	"get_dna_info",
	"get_record_author",
	"publish_ownership",
	"probe_shareds",
	"probe_owners",
	"create_shared_key",
	"send_shared_key",
	"request_shared_key",
	"query_shared_keys",
	"offer_ownership",
	"request_ownership",
	"cast_tip",
	"synchronize_tip",
];


/** Generate tuple array of function names with given zomeName */
export function generateSharedOwnershipZomeFunctionsArray(zomeName: ZomeName): [ZomeName, FunctionName][] {
   const fns: [ZomeName, FunctionName][] = [];
   for (const fn of sharedOwnershipFunctionNames) {
      fns.push([zomeName, fn]);
   }
   return fns;
}


/** Tuple array of all zome function names with default zome name "zSharedOwnership" */
export const sharedOwnershipZomeFunctions: [ZomeName, FunctionName][] = generateSharedOwnershipZomeFunctionsArray("zSharedOwnership");
