/* This file is generated by zits. Do not edit manually */

export enum SharedOwnershipUnitEnum {
	SharedKey = 'SharedKey',
}

/**
 * -------------------------------------------------------------------------------------------------
 * Link types
 * -------------------------------------------------------------------------------------------------
 */
export enum SharedOwnershipLinkType {
	SharedPath = 'SharedPath',
	SharedEntry = 'SharedEntry',
	Shared = 'Shared',
	Owner = 'Owner',
}
