/* This file is generated by zits. Do not edit manually */

// @ts-ignore
import {
/** api/common.ts */
// @ts-ignore
WebsocketConnectionOptions, WsClientOptions, HolochainError, CloneIdHelper,
/** types.ts */
// @ts-ignore
KitsuneAgent, KitsuneSpace, HoloHashB64, AgentPubKeyB64, DnaHashB64, WasmHashB64, EntryHashB64, ActionHashB64, AnyDhtHashB64, InstalledAppId, Signature, CellId, DnaProperties, RoleName, InstalledCell, Timestamp, HoloHashed, FetchPoolInfo,
/** hdk/action.ts */
// @ts-ignore
SignedAction, SignedActionHashed, RegisterAgentActivity, ActionHashed, ActionType, Action, NewEntryAction, Dna, AgentValidationPkg, InitZomesComplete, CreateLink, DeleteLink, OpenChain, CloseChain, Update, Delete, Create,
/** hdk/capabilities.ts */
// @ts-ignore
CapSecret, CapClaim, GrantedFunctionsType, GrantedFunctions, ZomeCallCapGrant, CapAccess, CapGrant,
///** hdk/countersigning.ts */
//CounterSigningSessionData,
//PreflightRequest,
//CounterSigningSessionTimes,
//ActionBase,
//CounterSigningAgents,
//PreflightBytes,
//Role,
//CountersigningAgentState,
/** hdk/dht-ops.ts */
// @ts-ignore
ChainOpType, DhtOp, WarrantOp, ChainOp, Warrant, ChainIntegrityWarrant, ValidationType, ActionHashAndSig,
/** hdk/entry.ts */
// @ts-ignore
EntryVisibility, AppEntryDef, EntryType, EntryContent, Entry,
/** hdk/record.ts */
// @ts-ignore
Record as HcRecord, RecordEntry as HcRecordEntry,
/** hdk/link.ts */
//AnyLinkableHash,
// @ts-ignore
ZomeIndex, LinkType, LinkTag, RateWeight, RateBucketId, RateUnits, Link,
/** api/admin/types.ts */
// @ts-ignore
// YamlProperties
Zomes, WasmCode, CapGrantInfo, PeerMetaInfo, DisabledAppReason, AppStatus, StemCell, ProvisionedCell, ClonedCell, CellType, CellInfo, AppInfo, MembraneProof, MemproofMap, RoleSettingsMap, RoleSettings, DnaModifiersOpt, DnaModifiers, FunctionName, ZomeName, ZomeDefinition, IntegrityZome, CoordinatorZome, DnaDefinition, ResourceBytes, ResourceMap, CellProvisioningStrategy, CellProvisioning, DnaVersionSpec, DnaVersionFlexible, AppRoleDnaManifest, AppRoleManifest, AppManifest, AppBundle, AppBundleSource, NetworkSeed, AppStatusFilter, AppInterfaceInfo, AgentInfoSigned, ZomeLocation, DnaManifest,
} from '@holochain/client';


/// Simple Hashes
// @ts-ignore
type AgentArray = Uint8Array;
// @ts-ignore
type DnaArray = Uint8Array;
// @ts-ignore
type WasmArray = Uint8Array;
// @ts-ignore
type EntryArray = Uint8Array;
// @ts-ignore
type ActionArray = Uint8Array;
// @ts-ignore
type AnyDhtArray = Uint8Array;
// @ts-ignore
type AnyLinkableArray = Uint8Array;
// @ts-ignore
type ExternalArray = Uint8Array;

// @ts-ignore
import {
/** Common */
// @ts-ignore
DhtOpHashB64, DhtOpHash,
/** DnaFile */
// @ts-ignore
DnaFile, DnaDef,
/** entry-details */
// @ts-ignore
EntryDetails, RecordDetails, Details, DetailsType, EntryDhtStatus,
/** Validation */
// @ts-ignore
ValidationStatus, ValidationReceipt,
} from '@holochain-open-dev/core-types';

/** ValidationStatus */
export enum ValidatedBy {
	None = 'None',
	Me = 'Me',
	Network = 'Network',
}

/** Bool: True if state change just happened (real-time) */
export enum StateChangeType {
	Create = 'Create',
	Update = 'Update',
	Delete = 'Delete',
}
export type StateChangeVariantCreate = {Create: boolean}
export type StateChangeVariantUpdate = {Update: boolean}
export type StateChangeVariantDelete = {Delete: boolean}
export type StateChange = 
 | StateChangeVariantCreate | StateChangeVariantUpdate | StateChangeVariantDelete;

/**  */
export interface LinkPulse {
  link: Link
  state: StateChange
  validation: ValidatedBy
}

export interface EntryPulse {
  state: StateChange
  validation: ValidatedBy
  orig_ah?: ActionArray
  ah: ActionArray
  eh: EntryArray
  ts: Timestamp
  author: AgentArray
  def: AppEntryDef
  bytes: Uint8Array
}

/**  */
export interface ZomeSignal {
  from: AgentArray
  pulses: ZomeSignalProtocol[]
}

/**  */
export enum ZomeSignalProtocolType {
	System = 'System',
	Entry = 'Entry',
	Link = 'Link',
	Tip = 'Tip',
}
export type ZomeSignalProtocolVariantSystem = {System: SystemAttestation}
export type ZomeSignalProtocolVariantEntry = {Entry: EntryPulse}
export type ZomeSignalProtocolVariantLink = {Link: LinkPulse}
export type ZomeSignalProtocolVariantTip = {Tip: TipProtocol}
export type ZomeSignalProtocol = 
 | ZomeSignalProtocolVariantSystem | ZomeSignalProtocolVariantEntry | ZomeSignalProtocolVariantLink | ZomeSignalProtocolVariantTip;

/** App-agnostic attestation */
export type SystemAttestationVariantPostCommitLink = {
  type: "PostCommitLink"
  link_type: number
  is_delete: boolean
  succeeded: boolean
}
export type SystemAttestationVariantPostCommitEntry = {
  type: "PostCommitEntry"
  app_entry_type: string
  is_delete: boolean
  succeeded: boolean
}
export type SystemAttestationVariantSelfCallStart = {
  type: "SelfCallStart"
  zome_name: string
  fn_name: string
}
export type SystemAttestationVariantSelfCallEnd = {
  type: "SelfCallEnd"
  zome_name: string
  fn_name: string
  succeeded: boolean
}
export type SystemAttestation =
  | SystemAttestationVariantPostCommitLink
  | SystemAttestationVariantPostCommitEntry
  | SystemAttestationVariantSelfCallStart
  | SystemAttestationVariantSelfCallEnd;

/** Protocol used by UI ONLY to send data to other agents */
export enum TipProtocolType {
	Ping = 'Ping',
	Pong = 'Pong',
	Entry = 'Entry',
	Link = 'Link',
	AppCustom = 'AppCustom',
	AppValue = 'AppValue',
}
export type TipProtocolVariantPing = {Ping: AgentArray}
export type TipProtocolVariantPong = {Pong: AgentArray}
export type TipProtocolVariantEntry = {Entry: EntryPulse}
export type TipProtocolVariantLink = {Link: LinkPulse}
export type TipProtocolVariantAppCustom = {AppCustom: Uint8Array}
export type TipProtocolVariantAppValue = {AppValue: [string, string]}
export type TipProtocol = 
 | TipProtocolVariantPing | TipProtocolVariantPong | TipProtocolVariantEntry | TipProtocolVariantLink | TipProtocolVariantAppCustom | TipProtocolVariantAppValue;

export interface CastTipInput {
  tip: TipProtocol
  peers: AgentArray[]
}

export interface SynchronizeTipInput {
  tip: TipProtocol
  recipient: AgentArray
  zomeName: string
}
