/* This file is generated by zits. Do not edit manually */

import {ZomeName, FunctionName} from '@holochain/client';


/** Array of all zome function names in "pathExplorer" */
export const pathExplorerFunctionNames: FunctionName[] = [
	"entry_defs", 
	"get_zome_info", 
	"get_dna_info",
	"get_my_agent_key_entry_hash",
	"get_record_author_from_local",
	"get_record_author_from_network",
	"get_record_from_local",
	"get_record_from_network",
	"get_ah_from_local",
	"get_ah_from_network",
	"get_data_type",
	"get_all_items_from_anchor_from_local",
	"get_all_items_from_anchor_from_network",
	"get_all_items_from_local",
	"get_all_items_from_network",
	"get_all_items_b64_from_network",
	"get_all_items_b64_from_local",
	"get_all_root_anchors",
	"get_items",
	"get_leafs_from_local",
	"get_leafs_from_network",
	"get_typed_anchor_network",
	"get_typed_anchor_local",
	"get_typed_children_from_local",
	"get_typed_children_from_network",
	"inspect_link",
];


/** Generate tuple array of function names with given zomeName */
export function generatePathExplorerZomeFunctionsArray(zomeName: ZomeName): [ZomeName, FunctionName][] {
   const fns: [ZomeName, FunctionName][] = [];
   for (const fn of pathExplorerFunctionNames) {
      fns.push([zomeName, fn]);
   }
   return fns;
}


/** Tuple array of all zome function names with default zome name "zPathExplorer" */
export const pathExplorerZomeFunctions: [ZomeName, FunctionName][] = generatePathExplorerZomeFunctionsArray("zPathExplorer");
