/* This file is generated by zits. Do not edit manually */

// @ts-ignore
import {GetAgentInput, GetAhInput, GetDataTypeInput, GetDhInput, GetEhInput, GetItemsInput, GetLhInput, GetManyAgentInput, GetManyAhInput, GetManyDhInput, GetManyEhInput, GetManyLhInput, HashInfo, MyLinkFilter, MyValidationReceiptInfo, MyValidationReceiptSet, TypedAnchor, } from './path-explorer.types';
// @ts-ignore
import {
/** api/common.ts */
// @ts-ignore
WebsocketConnectionOptions, WsClientOptions, HolochainError, CloneIdHelper,
/** types.ts */
// @ts-ignore
KitsuneAgent, KitsuneSpace, HoloHashB64, AgentPubKeyB64, DnaHashB64, WasmHashB64, EntryHashB64, ActionHashB64, AnyDhtHashB64, InstalledAppId, Signature, CellId, DnaProperties, RoleName, InstalledCell, Timestamp, HoloHashed, FetchPoolInfo,
/** hdk/action.ts */
// @ts-ignore
SignedAction, SignedActionHashed, RegisterAgentActivity, ActionHashed, ActionType, Action, NewEntryAction, Dna, AgentValidationPkg, InitZomesComplete, CreateLink, DeleteLink, OpenChain, CloseChain, Update, Delete, Create,
/** hdk/capabilities.ts */
// @ts-ignore
CapSecret, CapClaim, GrantedFunctionsType, GrantedFunctions, ZomeCallCapGrant, CapAccess, CapGrant,
///** hdk/countersigning.ts */
//CounterSigningSessionData,
//PreflightRequest,
//CounterSigningSessionTimes,
//ActionBase,
//CounterSigningAgents,
//PreflightBytes,
//Role,
//CountersigningAgentState,
/** hdk/dht-ops.ts */
// @ts-ignore
ChainOpType, DhtOp, WarrantOp, ChainOp, Warrant, ChainIntegrityWarrant, ValidationType, ActionHashAndSig,
/** hdk/entry.ts */
// @ts-ignore
EntryVisibility, AppEntryDef, EntryType, EntryContent, Entry,
/** hdk/record.ts */
// @ts-ignore
Record as HcRecord, RecordEntry as HcRecordEntry,
/** hdk/link.ts */
//AnyLinkableHash,
// @ts-ignore
ZomeIndex, LinkType, LinkTag, RateWeight, RateBucketId, RateUnits, Link,
/** api/admin/types.ts */
// @ts-ignore
// YamlProperties
Zomes, WasmCode, CapGrantInfo, PeerMetaInfo, DisabledAppReason, AppStatus, StemCell, ProvisionedCell, ClonedCell, CellType, CellInfo, AppInfo, MembraneProof, MemproofMap, RoleSettingsMap, RoleSettings, DnaModifiersOpt, DnaModifiers, FunctionName, ZomeName, ZomeDefinition, IntegrityZome, CoordinatorZome, DnaDefinition, ResourceBytes, ResourceMap, CellProvisioningStrategy, CellProvisioning, DnaVersionSpec, DnaVersionFlexible, AppRoleDnaManifest, AppRoleManifest, AppManifest, AppBundle, AppBundleSource, NetworkSeed, AppStatusFilter, AppInterfaceInfo, AgentInfoSigned, ZomeLocation, DnaManifest,
} from '@holochain/client';


/// Simple Hashes
// @ts-ignore
type AgentArray = Uint8Array;
// @ts-ignore
type DnaArray = Uint8Array;
// @ts-ignore
type WasmArray = Uint8Array;
// @ts-ignore
type EntryArray = Uint8Array;
// @ts-ignore
type ActionArray = Uint8Array;
// @ts-ignore
type AnyDhtArray = Uint8Array;
// @ts-ignore
type AnyLinkableArray = Uint8Array;
// @ts-ignore
type ExternalArray = Uint8Array;

// @ts-ignore
import {
/** Common */
// @ts-ignore
DhtOpHashB64, DhtOpHash,
/** DnaFile */
// @ts-ignore
DnaFile,
/** entry */
// @ts-ignore
EntryDefLocation, EntryDefLocationType, AppEntryDefLocation, GetOptions, GetStrategy,
/** entry-details */
// @ts-ignore
EntryDetails, RecordDetails, Details, DetailsType, EntryDhtStatus,
/** Validation */
// @ts-ignore
ValidationStatus, ValidationReceipt,
} from '@holochain-open-dev/core-types';

/** User defined external dependencies */
// @ts-ignore
import {ItemLink, SweepInterval, SweepResponse} from './deps.types';

import {ZomeProxy} from '@ddd-qc/lit-happ';
import {pathExplorerFunctionNames} from './path-explorer.fn';



/**
 *
 */
export class PathExplorerProxy extends ZomeProxy {
  static override readonly DEFAULT_ZOME_NAME = "zPathExplorer";
  static override readonly FN_NAMES = pathExplorerFunctionNames;
  static override readonly ENTRY_TYPES = [];
  static override readonly LINK_TYPES = [];
 
  async getMyAgentKeyEntryHash(): Promise<AnyLinkableArray> {
    return this.call('get_my_agent_key_entry_hash', null);
  }

  async getRecordAuthorFromLocal(dh: AnyDhtArray): Promise<AgentArray> {
    return this.call('get_record_author_from_local', dh);
  }

  async getRecordAuthorFromNetwork(dh: AnyDhtArray): Promise<AgentArray> {
    return this.call('get_record_author_from_network', dh);
  }

  async getRecordFromLocal(hash: AnyDhtArray): Promise<HcRecord | null> {
    return this.call('get_record_from_local', hash);
  }

  async getRecordFromNetwork(hash: AnyDhtArray): Promise<HcRecord | null> {
    return this.call('get_record_from_network', hash);
  }

  async getAhFromLocal(eh: EntryArray): Promise<ActionArray | null> {
    return this.call('get_ah_from_local', eh);
  }

  async getAhFromNetwork(eh: EntryArray): Promise<ActionArray | null> {
    return this.call('get_ah_from_network', eh);
  }

  async getDataType(input: GetDataTypeInput): Promise<string> {
    return this.call('get_data_type', input);
  }

  async getMyReceipts(ah: ActionArray): Promise<MyValidationReceiptSet[]> {
    return this.call('get_my_receipts', ah);
  }

  async getAllItemsFromAnchorFromLocal(leafAnchor: string): Promise<ItemLink[]> {
    return this.call('get_all_items_from_anchor_from_local', leafAnchor);
  }

  async getAllItemsFromAnchorFromNetwork(leafAnchor: string): Promise<ItemLink[]> {
    return this.call('get_all_items_from_anchor_from_network', leafAnchor);
  }

  async getAllItemsFromLocal(hash: AnyLinkableArray): Promise<ItemLink[]> {
    return this.call('get_all_items_from_local', hash);
  }

  async getAllItemsFromNetwork(hash: AnyLinkableArray): Promise<ItemLink[]> {
    return this.call('get_all_items_from_network', hash);
  }

  async getAllItemsB64FromNetwork(b64: string): Promise<ItemLink[]> {
    return this.call('get_all_items_b64_from_network', b64);
  }

  async getAllItemsB64FromLocal(b64: string): Promise<ItemLink[]> {
    return this.call('get_all_items_b64_from_local', b64);
  }

  async getAllRootAnchors(strategy: GetStrategy): Promise<TypedAnchor[]> {
    return this.call('get_all_root_anchors', strategy);
  }

  async getItems(input: GetItemsInput): Promise<ItemLink[]> {
    return this.call('get_items', input);
  }

  async getLeafsFromLocal(ta: TypedAnchor): Promise<TypedAnchor[]> {
    return this.call('get_leafs_from_local', ta);
  }

  async getLeafsFromNetwork(ta: TypedAnchor): Promise<TypedAnchor[]> {
    return this.call('get_leafs_from_network', ta);
  }

  async getTypedAnchorNetwork(anchor: string): Promise<[EntryHashB64, TypedAnchor | null]> {
    return this.call('get_typed_anchor_network', anchor);
  }

  async getTypedAnchorLocal(anchor: string): Promise<[EntryHashB64, TypedAnchor | null]> {
    return this.call('get_typed_anchor_local', anchor);
  }

  async getTypedChildrenFromLocal(parentTa: TypedAnchor): Promise<TypedAnchor[]> {
    return this.call('get_typed_children_from_local', parentTa);
  }

  async getTypedChildrenFromNetwork(parentTa: TypedAnchor): Promise<TypedAnchor[]> {
    return this.call('get_typed_children_from_network', parentTa);
  }

  async inspectLink(input: GetLhInput): Promise<HashInfo> {
    return this.call('inspect_link', input);
  }
}
