/* This file is generated by zits. Do not edit manually */

import {ZomeName, FunctionName} from '@holochain/client';


/** Array of all zome function names in "pathExplorer" */
export const pathExplorerFunctionNames: FunctionName[] = [
	"entry_defs", 
	"get_zome_info", 
	"get_dna_info",
	"get_agent_entry_hash",
	"get_all_items_from_anchor",
	"get_all_items",
	"get_all_items_from_b64",
	"get_all_root_anchors",
	"get_items",
	"get_leafs",
	"get_typed_anchor",
	"get_typed_children",
	"inspect_link",
];


/** Generate tuple array of function names with given zomeName */
export function generatePathExplorerZomeFunctionsArray(zomeName: ZomeName): [ZomeName, FunctionName][] {
   const fns: [ZomeName, FunctionName][] = [];
   for (const fn of pathExplorerFunctionNames) {
      fns.push([zomeName, fn]);
   }
   return fns;
}


/** Tuple array of all zome function names with default zome name "zPathExplorer" */
export const pathExplorerZomeFunctions: [ZomeName, FunctionName][] = generatePathExplorerZomeFunctionsArray("zPathExplorer");
