/* This file is generated by zits. Do not edit manually */

export enum NotificationsUnitEnum {
	TwilioCredentials = 'TwilioCredentials',
	Contact = 'Contact',
	SentNotification = 'SentNotification',
}

export enum NotificationsLinkType {
	TwilioCredentialsUpdates = 'TwilioCredentialsUpdates',
	NotificantToNotifiers = 'NotificantToNotifiers',
	ContactUpdates = 'ContactUpdates',
	AnchorToNotifiers = 'AnchorToNotifiers',
	SentNotificationUpdates = 'SentNotificationUpdates',
}
