[workspace]
resolver = "2"
members = [
  "zomes/integer",
  "zomes/integer_integrity",
  "zomes/label",
  "zomes/label_integrity",
  "zomes/real",
  "zomes/real_integrity",
  "zomes/tasker",
  "zomes/tasker_model",
  "zomes/profiles",
  "zomes/profiles_integrity",
  "zomes/agent_directory",
  "zomes/agent_directory_integrity",
  "zomes/path_explorer"
]

[workspace.package]
version = "2.0.0"
rust-version = "1.75.0"
edition = "2021"

[workspace.lints.rust]
non_upper_case_globals = "allow"
unused_doc_comments = "allow"
non_camel_case_types = "allow"
non_snake_case = "allow"
unused_attributes = "allow"

[workspace.dependencies]
holochain_serialized_bytes = "0.0.57"
serde = { version = "=1.0.228", default-features = false }
hdi = { version = "=0.7.1", default-features = false }
hdk = { version = "=0.6.1", default-features = false }

zome_utils = { path = "../submodules/zdk/crates/zome_utils" }
zome_signals = { path = "../submodules/zdk/crates/zome_signals" }
zome_core = { path = "../submodules/zdk/zomes/zome_core" }

hc_zome_profiles_integrity = { path = "../submodules/profiles/crates/integrity" }
profiles_alt_coordinator   = { path = "../submodules/zdk/zomes/profiles_alt_coordinator"}

agent_directory_integrity = { path = "../submodules/zdk/zomes/agent_directory_integrity" }
agent_directory           = { path = "../submodules/zdk/zomes/agent_directory" }

path_explorer             = { path = "../submodules/zdk/zomes/path_explorer" }

[profile.dev]
lto = false
opt-level = 0
overflow-checks = false

[profile.release]
opt-level = "z"
lto = true

[profile.release.build-override]
opt-level = "z"
