/* This file is generated by zits. Do not edit manually */

import {ZomeName, FunctionName} from '@holochain/client';


/** Array of all zome function names in "integer" */
export const integerFunctionNames: FunctionName[] = [
	"entry_defs", 
	"get_zome_info", 
	"get_dna_info",
	"get_integer",
	"create_blocking_integer",
	"create_integer",
	"get_my_values_local",
	"get_my_values",
	"get_my_values_incremental",
];


/** Generate tuple array of function names with given zomeName */
export function generateIntegerZomeFunctionsArray(zomeName: ZomeName): [ZomeName, FunctionName][] {
   const fns: [ZomeName, FunctionName][] = [];
   for (const fn of integerFunctionNames) {
      fns.push([zomeName, fn]);
   }
   return fns;
}


/** Tuple array of all zome function names with default zome name "zInteger" */
export const integerZomeFunctions: [ZomeName, FunctionName][] = generateIntegerZomeFunctionsArray("zInteger");
