/* This file is generated by zits. Do not edit manually */

import {ZomeName, FunctionName} from '@holochain/client';


/** Array of all zome function names in "label" */
export const labelFunctionNames: FunctionName[] = [
	"entry_defs", 
	"get_zome_info", 
	"get_dna_info",
	"get_label",
	"create_label",
	"get_my_labels",
];


/** Generate tuple array of function names with given zomeName */
export function generateLabelZomeFunctionsArray(zomeName: ZomeName): [ZomeName, FunctionName][] {
   const fns: [ZomeName, FunctionName][] = [];
   for (const fn of labelFunctionNames) {
      fns.push([zomeName, fn]);
   }
   return fns;
}


/** Tuple array of all zome function names with default zome name "zLabel" */
export const labelZomeFunctions: [ZomeName, FunctionName][] = generateLabelZomeFunctionsArray("zLabel");
