name: build-webhapps

on:
  workflow_call:

jobs:
  build-webhapps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Install npm dependencies
      - name: Install npm dependencies
        shell: bash
        run: |
          npm install
      # install rust toolchain (for building playgrounds)
      - name: install rust toolchain
        shell: bash
        run: |
          npm run install:rust
      # Download submodules
      - name: Download submodules
        shell: bash
        run: |
          npm run install:submodules
      # install hc tools
      - name: Install hc tools
        shell: bash
        run: |
          npm run install:hc
      # install zits
      - name: Install zits
        shell: bash
        run: |
          npm run install:zits
      # Build playground happs
      - name: Build playground happs
        shell: bash
        run: |
          CARGO_NET_GIT_FETCH_WITH_CLI=true npm run build:example:happs
      # Build packages
      - name: Build packages
        run: |
          npm run build:packages
      # Build playground webapps
      - name: Build playground webapp
        run: |
          npm run build:ui -w playgrounds/webapp
      # Build playground we-applet
      - name: Build playground we-applet
        run: |
          npm run build:ui -w playgrounds/we-applet
      # Regroup artifacts
      - name: Regroup artifacts
        run: |
          cp playgrounds/target/wasm32-unknown-unknown/release/*.wasm ./artifacts
      # List uploaded files
      - name: List uploaded files
        run: ls -R
        working-directory: ./artifacts
      # "upload" artifacts
      - uses: actions/upload-artifact@v4
        with:
          path: artifacts
