name: test-workflow

on:
  push:
    branches: [ main, 'hdk-*' ]
  pull_request:
    branches: [ main, 'hdk-*' ]

jobs:
  call-build:
    uses: ./.github/workflows/build-webhapps.yml
    secrets: inherit

  show-artifacts:
    needs: call-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Download previously uploaded artifacts
      - uses: actions/download-artifact@v5
        with:
          path: artifacts
      # Display artifacts folder
      - name: Display artifacts folder
        run: |
          pwd
          ls -la
        working-directory: artifacts